version: '3.9'

services:
  user-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: users-db
    ports:
      - "5433:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - proxy-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  device-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: devices-db
    ports:
      - "5434:5432"
    volumes:
      - device-db-data:/var/lib/postgresql/data
    networks:
      - proxy-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  auth-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth-db
    ports:
      - "5435:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - proxy-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  monitoring-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: monitoring-db
    ports:
      - "5436:5432"
    volumes:
      - monitoring-db-data:/var/lib/postgresql/data
    networks:
      - proxy-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3


  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: kalo
      RABBITMQ_DEFAULT_PASS: kalo
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq
    networks:
      - proxy-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  user-service:
    build:
      context: ./UserManagement
      dockerfile: Dockerfile
    image: user-service:latest
    environment:
      DB_IP: user-db
      DB_PORT: 5432
      DB_DBNAME: users-db
      DB_USER: postgres
      DB_PASSWORD: admin
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: kalo
      RABBITMQ_PASSWORD: kalo
    networks:
      - proxy-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.user-service.rule=PathPrefix(`/api1`)"
        - "traefik.http.routers.user-service.entrypoints=web"
        - "traefik.http.services.user-service.loadbalancer.server.port=8080"

  device-service:
    build:
      context: ./DeviceManagement
      dockerfile: Dockerfile
    image: device-service:latest
    environment:
      DB_IP: device-db
      DB_PORT: 5432
      DB_DBNAME: devices-db
      DB_USER: postgres
      DB_PASSWORD: admin
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: kalo
      RABBITMQ_PASSWORD: kalo
    networks:
      - proxy-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.device-service.rule=PathPrefix(`/api2`)"
        - "traefik.http.routers.device-service.entrypoints=web"
        - "traefik.http.services.device-service.loadbalancer.server.port=8081"

  auth-service:
    build:
      context: ./AuthManagement
      dockerfile: Dockerfile
    image: auth-service:latest
    environment:
      DB_IP: auth-db
      DB_PORT: 5432
      DB_DBNAME: auth-db
      DB_USER: postgres
      DB_PASSWORD: admin
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: kalo
      RABBITMQ_PASSWORD: kalo
    networks:
      - proxy-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.auth-service.rule=PathPrefix(`/api3`)"
        - "traefik.http.routers.auth-service.entrypoints=web"
        - "traefik.http.services.auth-service.loadbalancer.server.port=8083"

  monitoring-service:
    build:
      context: ./MonitoringService
      dockerfile: Dockerfile
    image: monitoring-service:latest
    environment:
      DB_IP: monitoring-db
      DB_PORT: 5432
      DB_DBNAME: monitoring-db
      DB_USER: postgres
      DB_PASSWORD: admin
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: kalo
      RABBITMQ_PASSWORD: kalo
      REPLICA_ID: "{{.Task.Slot}}"
      PORT: 8084

    networks:
      - proxy-network
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.monitoring-service.rule=PathPrefix(`/api4`)"
        - "traefik.http.routers.monitoring-service.entrypoints=web"
        - "traefik.http.services.monitoring-service.loadbalancer.server.port=8084"

  communication-service:
    build:
      context: ./CommunicationService
      dockerfile: Dockerfile
    image: communication-service:latest
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: kalo
      RABBITMQ_PASSWORD: kalo
      PORT: 8085
    ports:
      - target: 8085
        published: 8085
        protocol: tcp
        mode: host
    networks:
      - proxy-network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.communication-service.rule=PathPrefix(`/api5`)"
        - "traefik.http.routers.communication-service.entrypoints=web"
        - "traefik.http.services.communication-service.loadbalancer.server.port=8085"

  loadbalancer-service:
    build:
      context: ./LoadBalancerService
      dockerfile: Dockerfile
    image: loadbalancer-service:latest
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: kalo
      RABBITMQ_PASSWORD: kalo
      REPLICA_COUNT: 3
    networks:
      - proxy-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
      labels:
        - "traefik.enable=false"

  frontend:
    build:
      context: ./Frontend/energy-management-app
      dockerfile: Dockerfile
    image: frontend:latest
    networks:
      - proxy-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.frontend.rule=Host(`localhost`)"
        - "traefik.http.routers.frontend.entrypoints=web"
        - "traefik.http.services.frontend.loadbalancer.server.port=80"

  traefik:
    image: traefik:v3.0
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 8080
        published: 8082
        protocol: tcp
        mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # Traefik can listen to the Docker events
      - "./traefik.yml:/etc/traefik/traefik.yml:ro" # Static configuration file
      - "./dynamic:/etc/traefik/dynamic:ro" # Dynamic configuration files
      - "./logs:/var/log/traefik" # Log files
    networks:
      - proxy-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

# Define a shared network for all services
networks:
  proxy-network:
    driver: overlay
    attachable: true

volumes:
  user-db-data:
  device-db-data:
  auth-db-data:
  monitoring-db-data:
  rabbitmq-lib:
  rabbitmq-log: